apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
  labels:
    app: node-backend
spec:
  selector:
    app: node-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
